name: Jekyll site CI

on:
  push:
    branches: [ "main" ]  # 使用 main 分支，如果你的默认分支是 master 则改为 master
  pull_request:
    branches: [ "main" ]  # 同上

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true
    
    - name: Install Jekyll
      run: |
        gem install jekyll bundler
        bundle install
    
    - name: Build site
      run: bundle exec jekyll build
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        publish_branch: gh-pages  # 部署到 gh-pages 分支
        
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '_site' 